# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    # default configuration for services in *this* file
    _defaults:
        public: true      # Automatically injects dependencies in your services.
        autowire: true
        autoconfigure: true

    App\Domain\Strava\Strava:
        class: App\Tests\Domain\Strava\SpyStrava

    App\Infrastructure\Time\Clock\Clock:
        factory: [ 'App\Tests\Infrastructure\Time\Clock\PausedClock', 'fromString' ]
        arguments: [ '2023-10-17 16:15:04' ]

    App\Infrastructure\Time\Sleep:
        class: App\Tests\Infrastructure\Time\Sleep\NullSleep

    App\Infrastructure\ValueObject\Identifier\UuidFactory:
        class: App\Tests\Infrastructure\ValueObject\Identifier\FakeUuidFactory

    App\Domain\Weather\OpenMeteo\OpenMeteo:
        class: App\Tests\Domain\Weather\OpenMeteo\SpyOpenMeteo

    App\Infrastructure\Geocoding\Nominatim\Nominatim:
        class: App\Tests\Infrastructure\Geocoding\Nominatim\SpyNominatim

    App\Domain\Integration\Notification\Ntfy\Ntfy:
        class: App\Tests\Domain\Integration\Notification\Ntfy\SpyNotify

    App\Infrastructure\Time\ResourceUsage\ResourceUsage:
        class: App\Tests\Infrastructure\Time\ResourceUsage\FixedResourceUsage

    App\Infrastructure\Doctrine\MigrationRunner:
        class: App\Tests\Infrastructure\Doctrine\VoidMigrationRunner

    App\Infrastructure\FileSystem\PermissionChecker:
        class: App\Tests\Infrastructure\FileSystem\SuccessfulPermissionChecker