# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(APP_ENV): 'dev'
    env(APP_DEBUG): 0
    env(LOCK_DSN): 'flock'
    env(TZ): ''
    app.gear_maintenance: []

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Infrastructure\Exception\ErrorResponseExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    Linkin\Component\DoctrineNamingStrategy\ORM\Mapping\CamelCaseNamingStrategy:
        class: Linkin\Component\DoctrineNamingStrategy\ORM\Mapping\CamelCaseNamingStrategy

    Doctrine\Migrations\Version\DbalMigrationFactory: ~
    App\Infrastructure\Doctrine\Migrations\Factory\CommandBusAwareMigrationFactory:
        decorates: Doctrine\Migrations\Version\DbalMigrationFactory
        arguments: [ '@App\Infrastructure\Doctrine\Migrations\Factory\CommandBusAwareMigrationFactory.inner' ]

    App\Infrastructure\CQRS\Command\Bus\CommandBus:
        class: App\Infrastructure\CQRS\Command\Bus\InMemoryCommandBus
        arguments: [!tagged_iterator app.command_handler]

    App\Infrastructure\CQRS\Query\Bus\QueryBus:
        class: App\Infrastructure\CQRS\Query\Bus\InMemoryQueryBus
        arguments: [!tagged_iterator app.query_handler]

    App\Infrastructure\ValueObject\String\KernelProjectDir:
        factory: [ null, 'fromString' ]
        arguments: ['%kernel.project_dir%']

    App\Infrastructure\ValueObject\String\PlatformEnvironment:
        factory: [ null, 'from' ]
        arguments: ['%env(string:APP_ENV)%']

    App\Infrastructure\Time\Format\DateAndTimeFormat:
        factory: [ null, 'create' ]
        arguments: [
            '%app.config.appearance.date_format%',
            '%app.config.appearance.time_format%',
        ]

    App\Infrastructure\ValueObject\Time\SerializableTimezone:
        factory: [ null, 'fromOptionalString' ]
        arguments: ['%env(string:TZ)%']

    App\Infrastructure\ValueObject\Measurement\UnitSystem:
        factory: [ null, from ]
        arguments: [ '%app.config.appearance.unit_system%' ]

    App\Infrastructure\Localisation\Locale:
        factory: [ null, 'from' ]
        arguments: [ '%app.config.appearance.locale%' ]

    League\Flysystem\FilesystemOperator: '@default.storage'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    App\Domain\App\AppUrl:
        factory: [ null, 'fromString' ]
        arguments: [ '%app.config.general.app_url%' ]

    App\Domain\App\ProfilePictureUrl:
        factory: [ null, 'fromOptionalString' ]
        arguments: [ '%app.config.general.profile_picture_url%' ]

    App\Domain\Integration\Notification\Ntfy\NtfyUrl:
        factory: [ null, 'fromOptionalString' ]
        arguments: ['%app.config.general.ntfy_url%']

    App\Domain\Strava\StravaClientId:
        factory: [ null, 'fromString' ]
        arguments: ['%app.config.strava.client_id%']

    App\Domain\Strava\StravaClientSecret:
        factory: [ null, 'fromString' ]
        arguments: ['%app.config.strava.client_secret%']

    App\Domain\Strava\StravaRefreshToken:
        factory: [ null, 'fromString' ]
        arguments: ['%app.config.strava.refresh_token%']

    App\Domain\Strava\Athlete\AthleteBirthDate:
        factory: [ null, 'fromString' ]
        arguments: ['%app.config.general.athlete.birthday%']

    App\Domain\Strava\Athlete\MaxHeartRate\MaxHeartRateFormula:
        class: App\Domain\Strava\Athlete\MaxHeartRate\MaxHeartRateFormula
        factory: [ '@App\Domain\Strava\Athlete\MaxHeartRate\MaxHeartRateFormulas', 'determineFormula' ]
        arguments: ['%app.config.general.athlete.max_heart_rate_formula%']

    App\Domain\Strava\Activity\ImportActivities\ActivityVisibilitiesToImport:
        factory: [ null, from ]
        arguments:  ['%app.config.import.activity_visibilities_to_import%']

    App\Domain\Strava\Activity\ImportActivities\NumberOfNewActivitiesToProcessPerImport:
        factory: [ null, fromInt ]
        arguments:  ['%app.config.import.number_of_new_activities_to_process_per_import%']

    App\Domain\Strava\Activity\ImportActivities\ActivitiesToSkipDuringImport:
        factory: [ null, from ]
        arguments:  ['%app.config.import.activities_to_skip_during_import%']

    App\Domain\Strava\Activity\ImportActivities\SkipActivitiesRecordedBefore:
        class: App\Domain\Strava\Activity\ImportActivities\SkipActivitiesRecordedBefore
        factory: [ null, fromOptionalString ]
        arguments:  ['%app.config.import.skip_activities_recorded_before%']

    App\Domain\Strava\Activity\SportType\SportTypesToImport:
        factory: [ null, from ]
        arguments:  ['%app.config.import.sport_types_to_import%']

    App\Domain\Strava\Athlete\Weight\AthleteWeightHistory:
        factory: [ null, fromArray ]
        arguments: [ '%app.config.general.athlete.weight_history%', '@App\Infrastructure\ValueObject\Measurement\UnitSystem']

    App\Domain\Strava\Ftp\FtpHistory:
        factory: [ null, fromArray ]
        arguments: [ '%app.config.general.athlete.ftp_history%' ]

    App\Domain\Strava\Gear\Maintenance\GearMaintenanceConfig:
        factory: [ null, fromArray ]
        arguments: ['%app.gear_maintenance%']

    App\Domain\Strava\Gear\Maintenance\Task\Progress\MaintenanceTaskProgressCalculator:
        class: App\Domain\Strava\Gear\Maintenance\Task\Progress\MaintenanceTaskProgressCalculator
        arguments: [!tagged_iterator app.maintenance_progress_calculation]

    App\Domain\Zwift\ZwiftLevel:
        factory: [ null, fromOptionalString ]
        arguments: [ '%app.config.zwift.level%' ]

    App\Domain\Zwift\ZwiftRacingScore:
        factory: [ null, fromOptionalString ]
        arguments: [ '%app.config.zwift.racing_score%']