# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(APP_DEBUG): 0
    env(LOCK_DSN): 'flock'
    env(TZ): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Infrastructure\Exception\ErrorResponseExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    Linkin\Component\DoctrineNamingStrategy\ORM\Mapping\CamelCaseNamingStrategy:
        class: Linkin\Component\DoctrineNamingStrategy\ORM\Mapping\CamelCaseNamingStrategy

    Doctrine\Migrations\Version\DbalMigrationFactory: ~
    App\Infrastructure\Doctrine\Migrations\Factory\CommandBusAwareMigrationFactory:
        decorates: Doctrine\Migrations\Version\DbalMigrationFactory
        arguments: [ '@App\Infrastructure\Doctrine\Migrations\Factory\CommandBusAwareMigrationFactory.inner' ]

    App\Infrastructure\ValueObject\String\KernelProjectDir:
        factory: [ null, 'fromString' ]
        arguments: ['%kernel.project_dir%']

    App\Infrastructure\ValueObject\String\PlatformEnvironment:
        factory: [ App\Infrastructure\ValueObject\String\PlatformEnvironment, 'fromServer' ]

    App\Infrastructure\Time\Format\DateAndTimeFormat:
        factory: [ null, 'create' ]
        arguments: [
            '@=app_config("appearance.dateFormat")',
            '@=app_config("appearance.timeFormat")',
        ]

    App\Infrastructure\ValueObject\Time\SerializableTimezone:
        factory: [ null, 'fromOptionalString' ]
        arguments: ['%env(string:TZ)%']

    App\Infrastructure\ValueObject\Measurement\UnitSystem:
        factory: [ App\Infrastructure\ValueObject\Measurement\UnitSystem, from ]
        arguments: ['@=app_config("appearance.unitSystem")']

    App\Infrastructure\Localisation\Locale:
        factory: [ App\Infrastructure\Localisation\Locale, 'from' ]
        arguments: ['@=app_config("appearance.locale")']

    League\Flysystem\FilesystemOperator: '@default.storage'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    app.config:
        public: true # We need to access this service from the container in expressions
        class: App\Infrastructure\Config\AppConfig

    App\Domain\App\AppUrl:
        factory: [ null, 'fromString' ]
        arguments: ['@=app_config("general.appUrl")']

    App\Domain\App\ProfilePictureUrl:
        factory: [ null, 'fromOptionalString' ]
        arguments: ['@=app_config("general.profilePictureUrl")']

    App\Domain\Integration\Notification\Ntfy\NtfyUrl:
        factory: [ null, 'fromOptionalString' ]
        arguments: ['@=app_config("general.ntfyUrl")']

    App\Domain\Strava\StravaClientId:
        factory: [ null, 'fromString' ]
        arguments: ['%env(string:STRAVA_CLIENT_ID)%']

    App\Domain\Strava\StravaClientSecret:
        factory: [ null, 'fromString' ]
        arguments: ['%env(string:STRAVA_CLIENT_SECRET)%']

    App\Domain\Strava\StravaRefreshToken:
        factory: [ null, 'fromString' ]
        arguments: ['%env(string:STRAVA_REFRESH_TOKEN)%']

    App\Domain\Strava\Athlete\AthleteBirthDate:
        factory: [ null, 'fromString' ]
        arguments: ['@=app_config("general.athlete.birthday")']

    App\Domain\Strava\Athlete\MaxHeartRate\MaxHeartRateFormula:
        class: App\Domain\Strava\Athlete\MaxHeartRate\MaxHeartRateFormula
        factory: [ '@App\Domain\Strava\Athlete\MaxHeartRate\MaxHeartRateFormulas', 'determineFormula' ]
        arguments: ['@=app_config("general.athlete.maxHeartRateFormula")']

    App\Domain\Strava\Activity\ImportActivities\ActivityVisibilitiesToImport:
        factory: [ null, from ]
        arguments: ['@=app_config("import.activityVisibilitiesToImport")']

    App\Domain\Strava\Activity\ImportActivities\NumberOfNewActivitiesToProcessPerImport:
        factory: [ null, fromInt ]
        arguments: ['@=app_config("import.numberOfNewActivitiesToProcessPerImport")']

    App\Domain\Strava\Activity\ImportActivities\ActivitiesToSkipDuringImport:
        factory: [ null, from ]
        arguments: ['@=app_config("import.activitiesToSkipDuringImport")']

    App\Domain\Strava\Activity\ImportActivities\SkipActivitiesRecordedBefore:
        class: App\Domain\Strava\Activity\ImportActivities\SkipActivitiesRecordedBefore
        factory: [ null, fromOptionalString ]
        arguments: ['@=app_config("import.skipActivitiesRecordedBefore")']

    App\Domain\Strava\Activity\SportType\SportTypesToImport:
        factory: [ null, from ]
        arguments: ['@=app_config("import.sportTypesToImport")']

    App\Domain\Strava\Athlete\Weight\AthleteWeightHistory:
        factory: [ null, fromArray ]
        arguments: [
            '@=app_config("general.athlete.weightHistory")',
            '@App\Infrastructure\ValueObject\Measurement\UnitSystem'
        ]

    App\Domain\Strava\Ftp\FtpHistory:
        factory: [ null, fromArray ]
        arguments: ['@=app_config("general.athlete.ftpHistory")']

    App\Domain\Strava\Gear\Maintenance\GearMaintenanceConfig:
        factory: [ null, fromArray ]
        arguments: ['@=app_config("gearMaintenance", [])']

    App\Domain\Zwift\ZwiftLevel:
        factory: [ null, fromOptionalString ]
        arguments: ['@=app_config("zwift.level")']

    App\Domain\Zwift\ZwiftRacingScore:
        factory: [ null, fromOptionalString ]
        arguments: ['@=app_config("zwift.racingScore")']